application: citation-analysis
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.app
