application: citation-analysis
version: 6
runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  max_concurrent_requests: 30

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: lxml
  version: 2.3.5
- name: MySQLdb
  version: 1.2.4
- name: ssl
  version: latest

handlers:
- url: /api/.*
  script: main.app
- url: /author/crawl
  script: main.app
- url: /publication/crawl
  script: main.app
- url: /author/refresh
  script: main.app
- url: /publication/refresh
  script: main.app
- url: /css
  static_dir: ui/css
- url: /js
  static_dir: ui/js
- url: /partials
  static_dir: ui/partials
- url: .*
  static_dir: ui
